import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
/*import Web3 from "web3"
import Web3Modal from "web3modal"
import WalletConnectProvider from '@walletconnect/web3-provider'*/
//import { UserProvider } from '@auth0/nextjs-auth0'

const inter = Inter({ subsets: ['latin'] })

//  const provider_options ={

// };
/*if(typeof window !=="undefined"){
  const web3modal=new Web3Modal({
    network:'testnet',
    cacheProvider:true,
    //provider_options,
  });
}*/

export const metadata: Metadata = {
  title: 'Movie App using Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <nav className='px-10 py-5 bg-nav'>
          <Link prefetch href="/" className="text-xl font-bold text-white">
            CineCollective <span className='text-teal-400'>Critiques</span>
          </Link>
          <button className=" ml-5 mr-5 mb-2 float-right text-white
        bg-teal-600 hover:bg-teal-700 md:text-xs p-2 
          rounded-full cursor-pointer">
            Connect Wallet</button>
       </nav>
        {children}</body>
    </html>

  )
}
/*onClick={async()=>{
  const provider = await web3modal.connect();
  const web3 = new Web3(provider);
}}*/